### ISSUE TITLE
Add support for Safari

### ISSUE THREAD

**Issue by macdonst** [murtuzaalisurti/back-to-top#1]
This is a really cool web component and I hate to be “that guy” but by extending direction from `HTMLButtonElement` and using `is` it won’t work in Safari, because Apple won’t let us have nice things. They refuse to implement `is`.

My suggestion, and please feel free to tell me to get lost, is to switch it to a `HTMLElement` and use composition where your WC wraps a button element to provide functionality/styling.

Cheers

**Comment by murtuzaalisurti** [comment]
you are right, the support for the `is` attribute is not available in Safari. Initially, I thought to go with this autonomous custom element approach and just extending the `HTMLElement` class but then I thought since it's just a button, why not take the advantage of the current button element to be more specific. But, in the interest of all, I have raised a PR #2 which includes the refactor.

**Comment by macdonst** [comment]
@murtuzaalisurti cool, thanks for being open to my random feedback.
